### ISSUE TITLE
UX Work- Donate Page Discussion

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#101]
When a user selects the "Donate to Orcasound" CTA, there are 2 ways they can donate:
1.) Our Open Collective link: https://opencollective.com/orcasound
2.) Our GitHub sponsorship link: https://github.com/sponsors/orcasound

There should be a design solution to allow users to choose either the Open Collective or GitHub Sponsorship link.

Also, there is 1 URL to donate to specific volunteers: https://www.orcasound.net/hacker-hall-of-fame/, but then individual volunteers will have their own URL for donations- Patreon, Kickstarter, etc. (Right now, my link goes to my portfolio, which isn't how donations can be collected!). This "Hacker Hall of Fame" page needs redesign work, and ways to donate to individuals according to each person is a design challenge, which I'm thinking is going to be complicated.

We should discuss who and what will be designed.

**Comment by shiyizhengux** [comment]
Hi @UXBrendan , I've placed my final design in the Dev Design Figma file.
