### ISSUE TITLE
UX Work- Donate Page Hall of Fame Discussion

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#102]
- [x] Assign a designer

The "Hall of Fame" should serve 2 purposes:

1. Recognition of volunteers regardless of whether they are soliciting donations or not (right now, none are raising funds)
2. Communicating which volunteers are raising funds via donations and how to donate to them

We need to figure out a system in which Orcasound volunteers understand IF they can raise funds for their work at Orcasound and HOW they can submit their information (info about them and their work, URL to their donation platform) to be visible on the page

Just to be clear, this page should communicate both the recognition of all volunteers who make it into the Hall of Fame as well as how to donate to individual volunteers raising funds. This is a Content Strategy challenge using clear Information Architecture to clearly communicate information and functionality.

**Comment by PrernaChoubey** [comment]
Hey Brendan,

I just joined today. I want to work on this project. Is that okay?

**Comment by UXBrendan** [comment]
@cjallday7 

Wireframed some ideas, will design a quick and simple version for Release 1.

**Comment by PrernaChoubey** [comment]
Awesome! On it.

**Comment by PrernaChoubey** [comment]
I wireframed some ideas too. Here's the link: https://www.figma.com/file/snoBhjW6uHAbubHepA7U2n/OrcaSound?type=design&node-id=0%3A1&mode=design&t=ySXJoc2kuF8HM2KN-1

Please me know your thoughts and any changes I should make.

**Comment by UXBrendan** [comment]
@cjallday7 is continuing design work, will report next meeting.

**Comment by cjallday7** [comment]
Designs have been updated in the Orcahome Dev Design file. 

The design now includes the contribution of every volunteer (as it's been written), elimination of the color from the "Project Dividers" to just have copy. 

If there are any suggestions for better design, let me know. Otherwise, this design is ready for dev!

**Comment by PrernaChoubey** [comment]
The designs look awesome! I guess this is ready to go.

**Comment by cjallday7** [comment]
Updated the text to be the same size and added the navigation bars and footers to all designs. Closing this issue and these designs are ready for dev.
