### ISSUE TITLE
UX Work- Release 1 Navigation Bars for Desktop, Tablet, and Mobile

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#105]
**_User Story_**
AS an Orcasound user I WANT to use header and footer navigation bars that reflect Release 1 design SO THAT I can navigate Release 1 when deployed on the web.

**_Description_**
The intent of this story is to design interim navigation header and footer bars that include navigation needs for Release 1. Components in Figma need to be created so that the navigation bars are consistent throughout all designed pages that will be sent to development.

**_Notes:_**
- Historically, navigation bars have not been components in the Figma design, resulting in inconsistent navigation bars across pages
- Navigation bars are being researched and designed for a future release, so these navigation bars will only be needed for Release 1
- Design the bars and make them components in this file: https://www.figma.com/file/AKxnlPthLEMQyYrYuMWqOW/Orcahome-Dev-Design?type=design&mode=design&t=pQJQ5mIm0zUv6KoA-1
- Base your navigation design on the bars designed in the "Updated design sent to development 2022" design- https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcahome-%2F-Orcasound-Website-Redesign-2021?type=design&node-id=298-290&mode=design
- Nav items:
     - Home Page (icon in upper left)
     - Get Involved
     - About Us
     - Listen
     - Learn
     - Donate (icon)
     - Notify Me
     - Blog
     - Send Feedback
     - Socials
          - Facebook
          - GitHub
          - LinkedIn
          - YouTube
          - X (Twitter, but with new X logo)
          - Instagram 

**_Acceptance Criteria_**
GIVEN I navigate Release 1 using the header and footer bars WHEN I browse Orcasound THEN I am able to navigate all included pages in Release 1.

**Comment by UXBrendan** [comment]
@verabao 

Just checking in with you- how is design going for the navigation bars for desktop, tablet, and mobile?

**Comment by UXBrendan** [comment]
@verabao

Just checking in with you- how is design going for the navigation bars for desktop, tablet, and mobile?

**Comment by knightjek23** [comment]
@UXBrendan I'd be happy to step in and help with this :)

**Comment by verabao** [comment]
I’m 91% done. Please read my latest slack message.

Best,
Vera

**Comment by UXBrendan** [comment]
- [x] Make sure the completed nav bars are placed in the dev Figma file
