### ISSUE TITLE
UX Work: User Story for "Donate" page design update

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#110]
@shiyizhengux- Thanks so much for your design update work for the "Donate" page [UX Work- Donate Page Discussion](https://github.com/orcasound/product/issues/101)!

Your next task is to write a user story outlining your design update of the "Get Involved" page to assign to devs for production. You can find User Story resources here: [User Story Training](https://github.com/orcasound/product/wiki/2.-UX-Resources#user-story-training)

**Comment by shiyizhengux** [comment]
I've added a new user story - please check it out [here](https://github.com/orcasound/product/issues/114).
