### ISSUE TITLE
Form Shipnoise Team

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#117]
- [x] Write recruitment post for Slack
     - Draft here: https://miro.com/app/board/uXjVMmnmd38=/?moveToWidget=3458764573752352810&cot=14
- [x] Schedule kickoff meeting
     - Doodle poll here: https://doodle.com/meeting/participate/id/dPMX5Owe
- [x] Create roadmap
     - Roadmap here: https://miro.com/app/board/uXjVMmnmd38=/?moveToWidget=3458764573751974440&cot=14

**Comment by ghufronbahar** [comment]
Hi Brendan can i join this project?

**Comment by UXBrendan** [comment]
@ghufronbahar 

Sure. As long as you fill out the Doodle poll (posted in Slack), you will be invited to the kick off meeting that will be scheduled for the second week of January. Until then, enjoy the holidays!
