### ISSUE TITLE
9. Onboarding

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#20]
Write a UX project brief for the Onboarding project.

[Onboarding Project Brief](https://docs.google.com/document/d/1d0T41w6cVH3yOCXNaNMbOuyypqumpuCf/edit?usp=drive_link)

**Comment by jeniverede** [comment]
https://drive.google.com/file/d/1IV0i2O7GGbKia5lH-i8WsZCH242wjt-F/view?usp=share_link

**Comment by UXBrendan** [comment]
@jeniverede 

Thanks for doing a great job! I transferred the pdf to a Word doc and made some edits. You can access it in the link I posted above in the original comment for this issue. When you open it, it will open into a Google Docs browser tab.
