### ISSUE TITLE
Orcahome Redesign Call Catalog Labeling of Calls UX Update

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#24]
**_User Story_**
**AS** a Orcahome webpage visitor, I **WANT** to see labeled calls with the correct spectrogram in the call catalog card **SO THAT** I can select call and listen to a smaller number of calls before selecting the option to go to the full catalog.

**_Description_**
The intent of this story is to apply call labels to the calls that are visualized in the call catalog card on the main "Learn" content screen (see links below).

**_NOTES:_**

- Use Material UI for the styling
- [ ] When design is ready to be sent to production, please write user story in appropriate repo in the Orcasound Github
     - [ ] User story template (please download file- it is a MS Word Template, opening it will create a new document that you can fill out): https://docs.google.com/document/d/16CaKvAQzBrsAvKle0ieSUCQpYvCCXp8v/edit?usp=share_link&ouid=110838499857425540356&rtpof=true&sd=true
     - [ ] Please reach out to @UXBrendan to identify appropriate repo in the Orcasound Github 
- [ ] Please design for 3 device types: desktop, tablet, and mobile

**_Acceptance Criteria_**
**GIVEN** I open the Orcasound Learn page **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

Figma file design: https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj?node-id=858:2138#404099825

Call catalog to choose calls from: https://www.orcasound.net/data/product/SRKW/call-catalog/srkw-orca-call-catalog.html

Related issue: https://github.com/orcasound/orcahome/issues/44

**Comment by jeniverede** [comment]
Hi Brendan,
The first draft of the re-design is pasted below the main page/component in the Figma file.
I am not clear on where the spectogram image files for each call are saved. Can you advise?
Once I have those I will add them.

Once the desktop design is approved I will work on the tablet and mobile view.
Thanks, Jennifer

**Comment by UXBrendan** [comment]
@jeniverede 

Good question about the spectrogram files. I'll have to dig around and find them- I know that @scottveirs has uploaded them somewhere in a directory he manages. He's shown it to me before.

**Comment by scottveirs** [comment]
Hey @jeniverede you'll find 2018 draft PNGs made by a Python script here -- 
[https://github.com/orcasound/orcadata/tree/master/Spectrogram/Plots](https://github.com/orcasound/orcadata/tree/master/Spectrogram/Plots)

If you want them all at once, try cloning the whole orcadata repo...

**Comment by jeniverede** [comment]
@scottveirs - Thank you!

@UXBrendan - The files in the link are the same blue/green .png files currently used in the Figma file. 
In the Figma file all 6 use the same .png as a placeholder so I can replace them with the actual calls. 
Are you happy to use these blue/green .png files or is there another image file you would prefer using?

**Comment by UXBrendan** [comment]
@jeniverede 

I'll let you make the best design decision about what style spectrogram you want to use in the design. Whatever you choose from what's available is fine.

**Comment by jeniverede** [comment]
@UXBrendan 

These blue/green files are the only ones available as of now, so I will use them out of necessity. ;)
If we find other images we like better later we can swap them out.

**Comment by UXBrendan** [comment]
@jeniverede 

Thanks Jennifer! Let me know when your design is ready for me to look over, and we can discuss how to send it to the devs.

**Comment by jeniverede** [comment]
@UXBrendan 

I completed the designs for all three devices with the corresponding images for each call.
Give me your feedback when you have time. :)

**Comment by UXBrendan** [comment]
@jeniverede 

Thanks for doing that design work! Please schedule a time with me to go over the Figma file- I can provide feedback during our meeting.

https://calendly.com/ux-brendan-thatcher/meeting

**Comment by UXBrendan** [comment]
@jeniverede 

Can you please provide me with a link to the designs you did for this user story? I'd like to send them to production.

**Comment by jeniverede** [comment]
Hi Brendan,
https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcahome-%2F-Orcasound-Website-Redesign-2021?type=design&node-id=298%3A290&mode=design&t=U7bNQBFrK5GZc1Kt-1

**Comment by UXBrendan** [comment]
@UXBrendan 

Label only, specify specific spectrograms
