### ISSUE TITLE
Tasks that Jennifer assigns to Brendan

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#29]
**Content for Onboarding Project pages**
- [x]  Bioacoustic Dashboard
- [x] Design System
- [x] Global Navigation
- [x] Notifications
- [x] Orcahome
- [x] OrcaLearn
- [x] Orcasite
- [x] PARTNERSHIP: Acartia
- [x] Personae Development
- [x] Shipnoise

**Content for Onboarding Department pages**
- [x]  Analytics
- [x] Content Strategy
- [x] Onboarding Team
- [x] ReOps

**Leadership**
- [x] Project Lead
- [x] Product Manager
- [x] UX Manager

**Comment by jeniverede** [comment]
Content for Onboarding Project pages
- [ ] Orcahome
- [ ] Orcasite
- [ ] Orcalearn
- [ ] Shipnoise
- [ ] Bioacoustic Dashboard
- [ ] Acartia
- [ ] Notifications

Content for Onboarding Department pages
- [ ] Accessibility
- [ ] Analytics
- [ ] UX Leadership
- [ ] Onboarding Team (maybe I can write this content after seeing how you wrote the others?)
- [ ] Research Ops

**Comment by UXBrendan** [comment]
@jeniverede 

I just want you to know that I'm still planning on putting together the content requested above. I just reviewed the UX onboarding website you put together in a bit more detail than I have in the past, and it looks amazing! I have some nitpicky tweaks to suggest, but I'll do that later after providing you all requested content. Thanks for all your hard work!

**Comment by jeniverede** [comment]
@UXBrendan 

No worries, I'm happy to have your list of tweaks when you have time. :)

**Comment by UXBrendan** [comment]
@jeniverede 

I'm nearing the end of writing all the project briefs. I'll be providing requested content for the onboarding website soon.

**Comment by UXBrendan** [comment]
@jeniverede 

Here is the content you requested for the onboarding website: https://docs.google.com/document/d/1j2GQ_-BnfAWutuKJE9JTUOPz21oVi-tT/edit?usp=drive_link&ouid=110838499857425540356&rtpof=true&sd=true
