### ISSUE TITLE
Orcahome Redesign: "Get Involved" Page 4- Donate- Link and Label Update

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#34]
**_User Story_**
**AS** an Orcahome user I **WANT** to see logos linked to the home page and donate pages of the network organizations that Orcasound is a part of under the "Donate" heading **SO THAT** I can easily reach network organization home pages and donate pages.

**_Description_**
The intent of this story is to update the Orcahome redesign of the "Learn" Page for ONLY the Donate portion on the page.

**_NOTES:_**
- For each network organization logo, links for the home page and the donate page need to be clearly shown
- In redlines, please provide URLs for each network organization home page and donate page
- Header/Footer already completed on different pull request https://github.com/orcasound/orcahome/pull/14
- Related to this dev issue: [Website Redesign: "Get Involved" Page 4- Donate- UI#49](https://github.com/orcasound/orcahome/issues/49)
- Use Material UI for the styling
- Please do all design work in copied versions of the most recent designs for desktop, tablet, and mobile and design
     - **DO NOT** edit current designs, please make copies below and do design work on the copied designs

**Links to the Donate Pages**
- Orca Network: https://www.orcanetwork.org/donate
- Oceans Initiative: https://oceansinitiative.org/get-involved/
- Deep Green Wilderness: https://www.deepgreenwilderness.com/donate
- Whale Scout: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=7P57R2WS8MM8Q&source=url&ssrt=1695425459827 (This link go straight to the Paypal page)
- Pacmam: https://pacmam.org/wp/donate/
- Center for Whale Research: https://www.whaleresearch.com/supportcwr
- Port Townsend Marine Science Center: https://ptmsc.org/get-involved/donate
- The Whale Trail: https://thewhaletrail.org/connect/donate/
- F.O.L.K.S (Friends of Lime Kiln Society): https://folkssji.org/donate/
- Orca Behavior Institute: https://orcabehaviorinstitute.org/supporters/

_Please remove the logos of "Beam Reach", "Cetacean Research Technology" and "Colorado College", since they are not NGO and do not have a donate section in their websites._

**_Acceptance Criteria_**
**GIVEN** I open the Orcasound Get Involved page **WHEN** I look at the "Donate" section of the page **THEN** I see logos of network organizations with links to each home page and donate page for each organization.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290

**Comment by UXBrendan** [comment]
@UXBrendan 

@shiyizhengux will create documentation- link to donate page

A word of caution- if you go to the current Orcasound website, some links may no longer be valid. Please double check all URLs for validity.

**Comment by shiyizhengux** [comment]
Will do, thanks for the heads-up! @UXBrendan

**Comment by shiyizhengux** [comment]
I couldn't find the donation page for the following websites. Is it okay to just put a link to their homepage or contact page? Please let me know. @UXBrendan 

- Cetacean Research Technology
- Beam Reach
- Colorado College: https://www.coloradocollege.edu/us/giving/ (Only found the page to donate to the entire college.)

**Comment by UXBrendan** [comment]
@shiyizhengux 

Beam Reach and Colorado College are not nonprofits, so you can leave them out entirely. I'd do the same with Ceteacean Research Technology, as that does not sound like a non profit to me.

**Comment by CourtneyDruzak** [comment]
Updated links: 

The Center for Whale Research: https://www.whaleresearch.com/supportcwr
Deep Green Wilderness: https://www.deepgreenwilderness.com/donate
F.O.L.K.S: https://folkssji.org/donate/
Orca Behavior Institute: https://orcabehaviorinstitute.org/
Orca Conservancy: https://www.orcaconservancy.org/donate
Orca Network: https://www.orcanetwork.org/donate
Port Townsend Marine Science Center: https://ptmsc.org/get-involved/donate
Project SeaWolf: https://www.projectseawolf.org/projectseawolforg/How_to_Help.html
Sound Action: https://soundaction.org/
Vashon Nature Center: https://vashonnaturecenter.org/donate/
The Whale Trail: https://thewhaletrail.org/connect/donate/

**Comment by UXBrendan** [comment]
- [x] Write new user story for dev work
@UXBrendan

**Comment by UXBrendan** [comment]
@Vhighc replied to my request, requested that I write a new user story: https://github.com/orgs/orcasound/projects/15?pane=issue&itemId=24702067

**Comment by UXBrendan** [comment]
@Vhighc 

I finally wrote the user story to link our partner logos- https://github.com/orcasound/orcahome/issues/122

**Comment by Vhighc** [comment]
> @Vhighc 
> 
> I finally wrote the user story to link our partner logos- https://github.com/orcasound/orcahome/issues/122

LoL. All hypertext links are now attached to their respective logos, the fix is on my local currently i will make a  push for that ASAP.
