### ISSUE TITLE
Organize UX Team spreadsheet

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#48]
Organize UX Team spreadsheet:

https://docs.google.com/spreadsheets/d/13I7Aub14STjfVJPREtVdiUJpZG3SBxa4/edit?usp=sharing&ouid=114998196991908490567&rtpof=true&sd=true

**Projects and departments needing teams** (not in any stack ranked order)
1. PROJECT: Orcahome
2. PROJECT: Orcasite
3. PROJECT: OrcaLearn
4. PROJECT: Shipnoise
5. PROJECT: Bioacoustic Dashboard
6. PROJECT: Acartia
7. PROJECT: Notifications
8. PROJECT: Onboarding Website
9. PROJECT: Personae
10. PROJECT: Global Navigation
11. PROJECT: Content Strategy
12. DEPARTMENT: Accessibility 
13. DEPARTMENT: Analytics
14. DEPARTMENT: UX Leadership (UX Management, Product Management)
15. DEPARTMENT: ReOps

**Comment by sathya716** [comment]
Hello Brendan, Here is a Figma file with the projects, let's use this to discuss offline 

https://www.figma.com/file/zwZTk36KM1Sumxhf0ga85S/Projects-and-team-members?type=design&node-id=0%3A1&t=MsYKhDTmiKhkSwpt-1

**Comment by UXBrendan** [comment]
@sathya716 

I updated the description to include all project and departments that need teams.

**Comment by UXBrendan** [comment]
@sathya716 

Not sure if you're still working on this, but I have been working on the project briefs in preparation for building teams. Have you come up with a solution to be able to track who is on what team, including what role they have (Team Lead, UX Researcher, UX Designer, etc.)?

**Comment by sathya716** [comment]
Hello Brendan,

I have requested team leads to provide me with active team members list

Once i receive the list, i will update it on github

Thanks,
Sathya

**Comment by sathya716** [comment]
Hello Brendan, I have requested project leads to provide me with the list of active team members who are working on their projects. Once received,  I will update the Excel sheet

**Comment by sathya716** [comment]
Hello Brendan,

Update: I emailed a bunch of team leads and two people got back to me regarding their team members. I am updating it on my Figma

**Comment by UXBrendan** [comment]
This approach to managing volunteers isn't working. It's hard to manually keep the spreadsheet updated, as we have a high rate of turnover. Also, active team members can jump from project to project. I've been discussing with Rick about how we can do this a better way. Let's continue to have discussions about this.
