### ISSUE TITLE
Orcahome Redesign: Mini call catalog update

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/product#95]
User Story
AS a Orcahome webpage visitor, I WANT to see labeled calls with the correct spectrogram in the call catalog card SO THAT I can select call and listen to a smaller number of calls before selecting the option to go to the full catalog.

Description
The intent of this story is to apply call labels to the calls that are visualized in the call catalog card on the main "Learn" content screen (see links below).

**Design that needs to be updated:** 
![Image](https://github.com/orcasound/product/assets/65036138/3d9d6abc-526c-4755-8161-8810b9717601)

Link to mini call catalog to be updated: https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj?node-id=738:963&mode=design#563512641

Asset: Spectrogram calls: https://github.com/orcasound/orcadata/tree/master/Spectrogram/Plots

**Comment by UXBrendan** [comment]
@NayoBaez 

After discussing the design update for the mini call catalog, I have an idea for the large play and stop buttons on top of spectrogram image. Would it be possible to have the play and stop icons visible while the cursor is hovering over the image, but disappear when the cursor is removed from the image? This would only work on desktop. For tablet and mobile designs, the play button would disappear once selected. For tablet and mobile, could we introduce the player as shown in Jennifer's desktop design update? This may be a lot of development work, so let me know if this is feasible. We do have a constant inflow of devs, so you could pair program with someone if that would be helpful. Happy to discuss this at our next Orcahome Release 1 weekly stand up.

**Comment by NayoBaez** [comment]
I will discuss it with @Zekrom-7780 since he wrote part of the code that is ready to be pushed. Although i do think that it would be better to push the current code and then work on this as a part of a new release inside a new issue. This would most probably mean refactoring the code, which could take some time.

**Comment by Zekrom-7780** [comment]
Yes, I agree with @NayoBaez , let us push our code with the previous changes first, THEN we can work on this

**Comment by Zekrom-7780** [comment]
Otherwise, if we sit doing this, we won't have anything to see
